# Set the language.
language: go

# Set up global environment variables.
env:
  global:
    - DEPLOYMENT_TARGET=mutagenio/sidecar:latest

# Set up the build matrix.
matrix:
  include:
    - os: linux
      env:
        - GOOS=linux
        - GOARCH=amd64

# Require the use of Docker on Linux.
services:
  - docker

# Force a newer version of Docker CE on Linux.
addons:
  apt:
    packages:
      - docker-ce

# Set our Go version(s). We generally only support a specific version of Go at a
# time, usually the latest.
# NOTE: When specifying versions with a trailing 0 (e.g. 1.10), you need to
# enclose the version in quotation marks for YAML to treat it as a string rather
# than a float to be truncated:
# https://github.com/travis-ci/travis-ci/issues/9247
go:
  - "1.15.2"

# Skip the default install step.
install: true

# Run the build.
script:
  - scripts/ci/build.sh

# Deploy on master branch updates.
deploy:
  provider: script
  script: scripts/ci/deploy.sh
  on:
    branch: release

# Send notifications.
notifications:
  email:
    - bot@mutagen.io
